// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqekguatnrwxnizzmlwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZWtndWF0bnJ3eG5penptbHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDcxODEsImV4cCI6MjA2ODAyMzE4MX0.lOYf0-hkkBg7XoxzVtEekmbt8QCFskRMyR7GulqDWGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});